"use client";
import { useState } from "react";
import Shell from "@/components/Shell";
import { Panel, Head, Badge, Stat, Trace, Bars, Spark, Ring } from "@/components/ui";
import { opsRole, opsNav } from "@/lib/roles";
import { useT, t3 } from "@/lib/i18n";
import { MessageSquare, Mail, Smartphone, Phone, Bot, GitBranch, ShieldCheck, Clock, Send, UserCheck, Sparkles, Wrench, ToggleLeft, ToggleRight, ChevronRight } from "lucide-react";

type Ticket = { id: string; ch: "app" | "whatsapp" | "email" | "school" | "phone"; from: string; org: string; subject: string; cat: string; pri: "P1" | "P2" | "P3"; sla: string; state: "new" | "agent" | "human" | "waiting" | "solved"; conf: number; body: string; draft: string; sources: string[]; steps: Array<[string, string]> };

export default function Support() {
  const t = useT();
  const [tab, setTab] = useState<"inbox" | "flows" | "playbooks" | "metrics">("inbox");
  const tickets: Ticket[] = [
    { id: "T-2381", ch: "whatsapp", from: "Mrs. Adaeze", org: "Great Heights School", subject: t(t3("6 名学员 Unit 6 下载失败", "Six learners cannot download Unit 6", "Wanafunzi 6 hawawezi kupakua Unit 6")), cat: t(t3("下载 / 离线包", "Downloads / packs", "Upakuaji")), pri: "P1", sla: "0:42", state: "agent", conf: 0.86, body: t(t3("今天下午 6 个孩子的手机 Unit 6 一直下载失败，网络是 2G。", "Six children's phones keep failing to download Unit 6 this afternoon, on 2G.", "Simu 6 zimeshindwa kupakua Unit 6, kwenye 2G.")), draft: t(t3("Adaeze 老师您好。我们查到这 6 台设备今天下午都在 2G 网络下尝试了 3 次。已为这 6 名学员推送 Unit 6 的纯音频版（9 MB），今晚 02:00 学校缓存点会自动补齐完整版；明天上课前设备连教务室 Wi-Fi 即可同步。若仍失败，请回复设备编号。", "Hello Mrs. Adaeze. We see these six devices tried three times on 2G this afternoon. We have pushed the audio-only Unit 6 (9 MB) to those six learners, and the school cache point will fetch the full version at 02:00 tonight; connecting to the office Wi-Fi before class tomorrow will sync it. If it still fails, please reply with the device numbers.", "Habari Mwalimu Adaeze. Tumetuma toleo la sauti la Unit 6 (MB 9) kwa wanafunzi 6; hifadhi ya shule itakamilisha usiku.")), sources: [t(t3("分发日志 · 3 次失败 · 2G", "Delivery log · 3 failures · 2G", "Rekodi ya usambazaji")), t(t3("运行手册 §4 弱网下载", "Runbook §4 weak-network downloads", "Mwongozo §4")), t(t3("缓存点状态 · 在线", "Cache point · online", "Hifadhi · mtandaoni"))], steps: [["route", t(t3("分类：下载", "classify: downloads", "aina: upakuaji"))], ["ground", t(t3("检索：分发日志 + 手册", "ground: delivery log + runbook", "msingi: rekodi + mwongozo"))], ["recall", t(t3("召回：该校上周同类工单", "recall: same school, last week", "kumbuka: shule hiyo wiki iliyopita"))], ["verify", t(t3("动作：推送音频版（已执行，低风险）", "action: push audio pack (auto, low risk)", "kitendo: tuma sauti"))], ["human", t(t3("回复：待人审", "reply: awaiting human", "jibu: inasubiri mtu"))]] },
    { id: "T-2380", ch: "app", from: "Chidi Nwosu", org: "HSK1 · Great Heights A", subject: t(t3("忘记 PIN，无法切换账号", "Forgot PIN, cannot switch account", "Nimesahau PIN")), cat: t(t3("账号 / 登录", "Account / sign-in", "Akaunti")), pri: "P2", sla: "3:10", state: "human", conf: 0.52, body: t(t3("我忘了 PIN，Amara 的账号在用这部手机。", "I forgot my PIN and Amara's account is on this phone.", "Nimesahau PIN yangu.")), draft: t(t3("Chidi 你好。PIN 重置需要学校管理员或家长确认。我已把重置请求发给 Great Heights 的 Adaeze 老师，确认后你会在手机上收到新的 PIN。", "Hi Chidi. A PIN reset needs confirmation from your school admin or parent. I have sent the request to Mrs. Adaeze at Great Heights; once confirmed you will receive a new PIN on the phone.", "Habari Chidi. Kuweka upya PIN kunahitaji uthibitisho wa msimamizi.")), sources: [t(t3("政策：未成年人账号重置需监护人 / 校方", "Policy: minors' resets need guardian or school", "Sera: watoto")), t(t3("学校联络人：Adaeze", "School contact: Adaeze", "Mawasiliano: Adaeze"))], steps: [["route", t(t3("分类：账号", "classify: account", "aina: akaunti"))], ["ground", t(t3("检索：未成年人政策", "ground: minors policy", "msingi: sera"))], ["human", t(t3("涉及身份 → 转人工", "identity involved → human", "utambulisho → mtu"))]] },
    { id: "T-2379", ch: "email", from: "HR · Sino-Lagos Energy", org: "Enterprise", subject: t(t3("请提供 A 组 9 月出勤报表", "Request: Group A attendance report for September", "Ombi la ripoti ya mahudhurio")), cat: t(t3("报表", "Reports", "Ripoti")), pri: "P3", sla: "22:00", state: "agent", conf: 0.93, body: t(t3("需要 9 月 A 组出勤 CSV，用于内部结算。", "We need the September attendance CSV for Group A for internal settlement.", "Tunahitaji CSV ya mahudhurio.")), draft: t(t3("已附上 A 组 9 月 1 日至 30 日出勤报表（CSV 与 PDF），回放计入出勤。报表只含出勤与进度，不含员工的学习内容与对话记录。", "Attached is the Group A attendance report for 1–30 September (CSV and PDF); replays count as attendance. The report contains attendance and progress only, no learning content or conversation logs.", "Ripoti ya mahudhurio imeambatishwa.")), sources: [t(t3("HR 看板导出接口", "HR dashboard export", "Uhamishaji wa dashibodi")), t(t3("数据可见范围政策", "Data visibility policy", "Sera ya mwonekano"))], steps: [["route", t(t3("分类：报表", "classify: reports", "aina: ripoti"))], ["ground", t(t3("检索：HR 权限 + 导出", "ground: HR scope + export", "msingi: upeo wa HR"))], ["verify", t(t3("护栏：仅出勤字段", "guardrail: attendance fields only", "kizuizi: sehemu za mahudhurio"))], ["verify", t(t3("自动发送（置信 93% ≥ 90%）", "auto-send (confidence 93% ≥ 90%)", "tuma kiotomatiki"))]] },
    { id: "T-2378", ch: "school", from: "New Horizon · WeChat group", org: "New Horizon School", subject: t(t3("周三直播是否受停电影响", "Will Wednesday's live class be affected by the power cut?", "Je, somo la Jumatano litaathiriwa?")), cat: t(t3("排课 / 直播", "Schedule / live", "Ratiba")), pri: "P2", sla: "1:30", state: "waiting", conf: 0.88, body: t(t3("周三 19:00–21:00 预报停电。", "A power cut is forecast on Wednesday 19:00–21:00.", "Umeme utakatika Jumatano.")), draft: t(t3("王老师已把周三直播提前到 16:00 WAT，并加了周四答疑；日历已更新，学员端会收到三语提醒。", "Wang Laoshi has moved Wednesday's live class to 16:00 WAT and added a Thursday Q&A; calendars are updated and learners receive reminders in three languages.", "Somo limehamishwa hadi 16:00 WAT.")), sources: [t(t3("排课变更记录", "Schedule change log", "Rekodi ya ratiba")), t(t3("停电预报接入", "Power-cut forecast feed", "Utabiri wa umeme"))], steps: [["route", t(t3("分类：排课", "classify: schedule", "aina: ratiba"))], ["recall", t(t3("召回：老师已采纳排课建议", "recall: teacher accepted reschedule", "kumbuka: mwalimu alikubali"))], ["verify", t(t3("回复已发送，等待学校确认", "reply sent, awaiting school", "jibu limetumwa"))]] },
    { id: "T-2377", ch: "phone", from: "Parent · Fatima's mother", org: "Great Heights School", subject: t(t3("希望删除孩子的语音录音", "Asks to delete her child's voice recordings", "Anaomba kufuta rekodi za sauti")), cat: t(t3("数据请求", "Data request", "Ombi la data")), pri: "P1", sla: "47:00", state: "human", conf: 0.71, body: t(t3("家长来电，要求删除 Fatima 的发音练习录音。", "Parent called asking to delete Fatima's pronunciation recordings.", "Mzazi aliomba kufuta rekodi.")), draft: t(t3("已登记数据删除请求（编号 DSR-118），将在 48 小时内完成并向家长书面确认；删除范围：发音练习录音，不影响成绩记录。", "Data deletion request logged (DSR-118), to be completed within 48 hours with written confirmation to the parent; scope: pronunciation recordings, scores unaffected.", "Ombi la kufuta data limeandikwa (DSR-118).")), sources: [t(t3("PDPA / NDPA 数据主体权利流程", "PDPA / NDPA data-subject procedure", "Utaratibu wa haki za data")), t(t3("审计留痕：DSR-118", "Audit trail: DSR-118", "Nyayo za ukaguzi"))], steps: [["route", t(t3("分类：数据请求", "classify: data request", "aina: ombi la data"))], ["ground", t(t3("检索：删除流程", "ground: deletion procedure", "msingi: utaratibu"))], ["human", t(t3("合规动作一律人审", "compliance actions always human", "vitendo vya uzingatiaji: mtu"))]] },
  ];
  const [selId, setSelId] = useState(tickets[0].id);
  const sel = tickets.find((k) => k.id === selId) ?? tickets[0];
  const [sent, setSent] = useState<string[]>([]);
  const chIcon = { app: MessageSquare, whatsapp: Smartphone, email: Mail, school: MessageSquare, phone: Phone };
  const chName = { app: t(t3("站内助手", "In-app assistant", "Msaidizi")), whatsapp: "WhatsApp", email: t(t3("邮件", "Email", "Barua pepe")), school: t(t3("学校群", "School group", "Kikundi cha shule")), phone: t(t3("电话", "Phone", "Simu")) };
  const stLabel = (s: Ticket["state"]) => t(s === "new" ? t3("新", "New", "Mpya") : s === "agent" ? t3("智能体处理中", "Agent working", "Wakala anafanya kazi") : s === "human" ? t3("待人工", "Needs human", "Inahitaji mtu") : s === "waiting" ? t3("等待对方", "Waiting", "Inasubiri") : t3("已解决", "Solved", "Imetatuliwa"));
  const stTone = (s: Ticket["state"]) => (s === "human" ? "bad" : s === "agent" ? "acc" : s === "waiting" ? "warn" : s === "solved" ? "good" : "");

  const [flows, setFlows] = useState([
    { k: t(t3("意图分类", "Intent classification", "Uainishaji wa nia")), d: t(t3("确定性启发式 + 模型兜底；输出类别与置信度", "Deterministic heuristics with model fallback; outputs category and confidence", "Heuristiki + modeli")), on: true },
    { k: t(t3("知识检索 · TIDAR KAG", "Knowledge retrieval · TIDAR KAG", "Urejeshaji wa maarifa")), d: t(t3("运行手册、政策、分发与排课日志，带出处", "Runbooks, policies, delivery and schedule logs, with sources", "Miongozo, sera, rekodi")), on: true },
    { k: t(t3("上下文召回", "Context recall", "Kumbukumbu ya muktadha")), d: t(t3("同一学校 / 学员的历史工单与班主任智能体 记录", "Past tickets for the same school or learner, homeroom agent notes", "Tiketi za awali")), on: true },
    { k: t(t3("只读工具", "Read-only tools", "Zana za kusoma tu")), d: t(t3("查设备状态、下载记录、出勤、缓存点", "Check device status, downloads, attendance, cache point", "Angalia hali ya kifaa")), on: true },
    { k: t(t3("低风险写动作（自动）", "Low-risk write actions (auto)", "Vitendo vya hatari ndogo")), d: t(t3("推送音频包、重发链接、改提醒时间；白名单内自动执行并留痕", "Push audio pack, resend link, change reminder time; whitelisted, auto-executed, logged", "Tuma kifurushi, tuma tena kiungo")), on: true },
    { k: t(t3("高风险写动作（提议 → 审批）", "High-risk write actions (propose → approve)", "Vitendo vya hatari kubwa")), d: t(t3("退费、改成绩、删除数据、改排课：智能体只提议，人批准后执行", "Refunds, score changes, data deletion, reschedules: agent proposes, human approves", "Wakala hupendekeza, mtu huidhinisha")), on: true },
    { k: t(t3("草拟回复 · 三语", "Draft reply · 3 languages", "Rasimu ya jibu")), d: t(t3("按对方语言草拟，附出处；老师音色语音版可选", "Drafted in the requester's language with sources; optional teacher-voice audio", "Rasimu kwa lugha ya mwombaji")), on: true },
    { k: t(t3("护栏检查", "Guardrail check", "Ukaguzi wa vizuizi")), d: t(t3("PII 去标识、越权、超纲、承诺类措辞拦截", "PII de-identification, scope, off-policy and promise-language blocks", "Kuondoa PII, upeo")), on: true },
    { k: t(t3("自动发送门槛", "Auto-send threshold", "Kizingiti cha kutuma kiotomatiki")), d: t(t3("置信 ≥ 90% 且类别在白名单（报表、下载、排课通知）才自动发送，其余人审", "Auto-send only at ≥ 90% confidence and whitelisted categories (reports, downloads, schedule notices); everything else goes to a human", "Tuma kiotomatiki ≥ 90% tu")), on: true },
  ]);

  return (
    <Shell role={opsRole} nav={opsNav} title={t3("客服中心", "Support centre", "Kituo cha usaidizi")} sub={t3("多渠道工单 · 可编排的 JE 智能体协助处理：分类 → 检索 → 召回 → 动作 → 草拟 → 护栏 → 人审或自动发送", "Multi-channel tickets · orchestrable JE Agent assists: classify → ground → recall → act → draft → guardrails → human or auto-send", "Tiketi za njia nyingi · JE Agent inayoweza kupangwa")} net={3}>
      <div className="grid c4" style={{ marginBottom: 16 }}>
        <Panel className="in in-1"><Stat value={7} label={t3("待处理工单", "open tickets", "tiketi zilizo wazi")} /></Panel>
        <Panel className="in in-2"><Stat value={68} suffix="%" label={t3("智能体自动解决率（本周）", "auto-resolved by agent (this week)", "zilizotatuliwa na wakala")} delta="+9%" /></Panel>
        <Panel className="in in-3"><Stat value={4} label={t3("首响中位数（分钟）", "median first response (min)", "jibu la kwanza (dakika)")} up delta="−11" /></Panel>
        <Panel className="in in-4"><Stat value={4.7} label={t3("满意度 / 5（学校与家长）", "satisfaction / 5 (schools and parents)", "kuridhika / 5")} /></Panel>
      </div>
      <div className="tabs"><button className={tab === "inbox" ? "on" : ""} onClick={() => setTab("inbox")}>{t(t3("工单收件箱", "Ticket inbox", "Kikasha cha tiketi"))}</button><button className={tab === "flows" ? "on" : ""} onClick={() => setTab("flows")}>{t(t3("智能体编排", "Agent orchestration", "Upangaji wa wakala"))}</button><button className={tab === "playbooks" ? "on" : ""} onClick={() => setTab("playbooks")}>{t(t3("处置手册", "Playbooks", "Miongozo"))}</button><button className={tab === "metrics" ? "on" : ""} onClick={() => setTab("metrics")}>{t(t3("质量与 SLA", "Quality & SLA", "Ubora na SLA"))}</button></div>

      {tab === "inbox" && (
        <div className="grid" style={{ gridTemplateColumns: "minmax(0,5fr) minmax(0,7fr)" }}>
          <Panel lift={false} className="in" style={{ padding: 12 }}>
            <div className="row" style={{ padding: "4px 8px 10px" }}>{[t(t3("全部", "All", "Zote")), t(t3("待人工", "Needs human", "Inahitaji mtu")), t(t3("智能体处理中", "Agent working", "Wakala")), t(t3("P1", "P1", "P1"))].map((c, i) => <span key={i} className={`chip ${i === 0 ? "on" : ""}`}>{c}</span>)}</div>
            <ul className="list">
              {tickets.map((k) => { const I = chIcon[k.ch]; const s = sent.includes(k.id) ? "solved" : k.state; return (
                <li key={k.id} onClick={() => setSelId(k.id)} style={{ cursor: "pointer", padding: "12px 8px", borderRadius: 10, background: sel.id === k.id ? "var(--panel-2)" : undefined }}>
                  <span className={`avatar ${k.pri === "P1" ? "" : k.pri === "P2" ? "gold" : "green"}`} style={{ width: 34, height: 34, fontSize: 10 }}>{k.pri}</span>
                  <div className="t"><b>{k.subject}</b><span><I size={11} /> {chName[k.ch]} · {k.from} · {k.org}</span></div>
                  <div style={{ textAlign: "right" }}><Badge tone={stTone(s)}>{stLabel(s)}</Badge><div className="small mono mute" style={{ marginTop: 4 }}><Clock size={10} /> SLA {k.sla}</div></div>
                </li>); })}
            </ul>
          </Panel>
          <Panel lift={false} glow className="in in-2">
            <div className="between"><div><div className="eyebrow">{sel.id} · {sel.cat} · {sel.pri}</div><h3 style={{ fontSize: 20, marginTop: 4 }}>{sel.subject}</h3><div className="small mute">{sel.from} · {sel.org} · {chName[sel.ch]}</div></div><Badge tone={stTone(sent.includes(sel.id) ? "solved" : sel.state)}>{stLabel(sent.includes(sel.id) ? "solved" : sel.state)}</Badge></div>
            <div className="chat" style={{ marginTop: 16 }}><div className="msg ai"><b style={{ fontSize: 12 }}>{sel.from}</b><div>{sel.body}</div></div></div>
            <div style={{ marginTop: 16 }}><div className="eyebrow" style={{ marginBottom: 8 }}><Bot size={12} /> {t(t3("JE 智能体处理轨迹", "JE Agent trace", "Nyayo za JE Agent"))}</div><Trace steps={sel.steps} /></div>
            <div style={{ marginTop: 16, padding: 14, borderRadius: 12, background: "var(--panel-2)", border: "1px solid var(--line)" }}>
              <div className="between"><div className="eyebrow"><Sparkles size={12} /> {t(t3("草拟回复", "Draft reply", "Rasimu ya jibu"))} · {t(t3("置信度", "confidence", "uhakika"))} {Math.round(sel.conf * 100)}%</div><Badge tone={sel.conf >= .9 ? "good" : "warn"}>{sel.conf >= .9 ? t(t3("可自动发送", "Auto-send eligible", "Inaweza kutumwa")) : t(t3("需人审", "Human review", "Ukaguzi wa mtu"))}</Badge></div>
              <p style={{ marginTop: 8, fontSize: 14, lineHeight: 1.7 }}>{sel.draft}</p>
              <div className="row" style={{ marginTop: 10, gap: 6 }}>{sel.sources.map((s) => <Badge key={s} tone="acc">{s}</Badge>)}</div>
            </div>
            <div className="row" style={{ marginTop: 14 }}>
              <button className="btn btn--primary" onClick={() => setSent([...sent, sel.id])}><Send size={14} /> {t(t3("按草稿发送", "Send draft", "Tuma rasimu"))}</button>
              <button className="btn"><Wrench size={14} /> {t(t3("修改后发送", "Edit and send", "Hariri na utume"))}</button>
              <button className="btn btn--ghost"><UserCheck size={14} /> {t(t3("转给王老师", "Assign to Wang Laoshi", "Kabidhi kwa Wang Laoshi"))}</button>
              <span className="small mute" style={{ marginLeft: "auto" }}>{t(t3("每次发送写入审计链，老师与家长可见来源", "Every send is written to the audit chain; sources are visible to teacher and parent", "Kila utumaji huandikwa"))}</span>
            </div>
          </Panel>
        </div>
      )}

      {tab === "flows" && (
        <div className="grid c3">
          <Panel className="span2 in" lift={false}><Head title={t3("客服智能体流水线（可编排）", "Support agent pipeline (orchestrable)", "Mchakato wa wakala wa usaidizi")} right={<Badge tone="good"><GitBranch size={12} /> v0.4 · {t(t3("灰度 30%", "canary 30%", "canary 30%"))}</Badge>} />
            <ol className="tl">{flows.map((f, i) => <li key={i} className={f.on ? "" : "todo"} style={{ display: "flex", gap: 12, alignItems: "flex-start" }}><button onClick={() => setFlows(flows.map((x, j) => (j === i ? { ...x, on: !x.on } : x)))} style={{ marginTop: 2, color: f.on ? "var(--good)" : "var(--dim)" }}>{f.on ? <ToggleRight size={22} /> : <ToggleLeft size={22} />}</button><div><b>{f.k}</b><div className="small mute">{f.d}</div></div></li>)}</ol>
            <div className="row" style={{ marginTop: 10 }}><button className="btn btn--primary btn--sm">{t(t3("保存为新版本并评估", "Save as new version and evaluate", "Hifadhi toleo jipya"))}</button><button className="btn btn--sm">{t(t3("回滚到 v0.3", "Roll back to v0.3", "Rudi kwa v0.3"))}</button></div>
          </Panel>
          <div className="grid" style={{ alignContent: "start" }}>
            <Panel className="in in-2" gold><Head title={t3("边界", "Boundaries", "Mipaka")} /><ul className="list small"><li><ShieldCheck size={14} color="var(--good)" /><div className="t"><b>{t(t3("智能体永远没有写权限", "The agent never holds write permission", "Wakala hana ruhusa ya kuandika"))}</b><span>{t(t3("白名单低风险动作由系统执行并留痕", "Whitelisted low-risk actions are executed by the system and logged", "Vitendo vya hatari ndogo hutekelezwa na mfumo"))}</span></div></li><li><ShieldCheck size={14} color="var(--good)" /><div className="t"><b>{t(t3("涉及身份、资金、数据、成绩一律人审", "Identity, money, data and scores always go to a human", "Utambulisho, pesa, data: mtu"))}</b></div></li><li><ShieldCheck size={14} color="var(--good)" /><div className="t"><b>{t(t3("每条回复带出处", "Every reply carries sources", "Kila jibu lina vyanzo"))}</b><span>{t(t3("没有出处就转人工", "No source, no auto-reply", "Bila chanzo, hakuna jibu la kiotomatiki"))}</span></div></li></ul></Panel>
            <Panel className="in in-3"><Head title={t3("接入渠道", "Channels", "Njia")} /><ul className="list small">{[[MessageSquare, t(t3("站内助手（学员 / 老师 / 学校）", "In-app assistant (learner / teacher / school)", "Msaidizi wa ndani")), "good"], [Smartphone, "WhatsApp Business", "good"], [Mail, "support@gacee.org", "good"], [MessageSquare, t(t3("学校微信群（人工转录）", "School WeChat groups (manual capture)", "Vikundi vya WeChat")), "warn"], [Phone, t(t3("电话（记录为工单）", "Phone (logged as ticket)", "Simu")), "warn"]].map(([I, n, s], i) => { const Ic = I as typeof MessageSquare; return <li key={i}><Ic size={14} /><div className="t"><b>{n as string}</b></div><Badge tone={s as never}>{s === "good" ? t(t3("已接入", "Connected", "Imeunganishwa")) : t(t3("半自动", "Semi-automatic", "Nusu-otomatiki"))}</Badge></li>; })}</ul></Panel>
          </div>
        </div>
      )}

      {tab === "playbooks" && (
        <div className="grid c3">
          {[[t(t3("下载 / 离线包失败", "Download / pack failure", "Upakuaji umeshindwa")), t(t3("查分发日志 → 推纯音频版 → 夜间缓存点补齐 → 次日确认", "Check delivery log → push audio-only → cache point tops up at night → confirm next day", "Angalia rekodi → tuma sauti → hifadhi usiku")), "auto", 142], [t(t3("PIN / 账号切换", "PIN / account switch", "PIN / akaunti")), t(t3("核验身份 → 学校或家长确认 → 重置 → 通知", "Verify identity → school or parent confirms → reset → notify", "Thibitisha → mzazi → weka upya")), "human", 58], [t(t3("停电与补课", "Power cuts & catch-up", "Kukatika kwa umeme")), t(t3("对照预报 → 提议改期 → 老师采纳 → 三语提醒 → 回放排入离线包", "Match forecast → propose reschedule → teacher accepts → reminders → replay into offline pack", "Linganisha utabiri → pendekeza")), "propose", 37], [t(t3("家长同意与数据请求", "Consent & data requests", "Idhini na maombi ya data")), t(t3("登记 DSR → 48 小时内执行 → 书面确认 → 审计留痕", "Log DSR → execute within 48 h → written confirmation → audit trail", "Andika DSR → tekeleza → thibitisha")), "human", 9], [t(t3("报表与证书", "Reports & certificates", "Ripoti na vyeti")), t(t3("校验权限范围 → 生成 → 自动发送", "Check scope → generate → auto-send", "Kagua upeo → unda → tuma")), "auto", 64], [t(t3("翻译有误反馈", "Translation error reports", "Makosa ya tafsiri")), t(t3("入语言包审核队列 → 审校 → 发布", "Into the language-pack review queue → review → publish", "Kwenye foleni ya lugha")), "auto", 12]].map(([n, d, mode, cnt], i) => <Panel key={i} className={`in in-${i + 1}`}><div className="between"><b>{n as string}</b><Badge tone={mode === "auto" ? "good" : mode === "propose" ? "warn" : "bad"}>{mode === "auto" ? t(t3("自动", "Auto", "Otomatiki")) : mode === "propose" ? t(t3("提议 → 审批", "Propose → approve", "Pendekeza → idhinisha")) : t(t3("人工", "Human", "Mtu"))}</Badge></div><p className="small mute" style={{ marginTop: 8, lineHeight: 1.7 }}>{d as string}</p><div className="small dim" style={{ marginTop: 10 }}>{cnt as number} {t(t3("次 · 本月", "this month", "mwezi huu"))} <ChevronRight size={12} /></div></Panel>)}
        </div>
      )}

      {tab === "metrics" && (
        <div className="grid c3">
          <Panel className="in"><Head title={t3("解决方式 · 本周", "Resolution mix · this week", "Njia ya utatuzi")} /><Bars data={[68, 19, 13]} labels={[t(t3("智能体自动", "Agent auto", "Wakala")), t(t3("智能体草拟 + 人审", "Draft + human", "Rasimu + mtu")), t(t3("纯人工", "Human only", "Mtu tu"))]} color="var(--accent)" h={120} /></Panel>
          <Panel className="in in-2"><Head title={t3("SLA 达成", "SLA attainment", "Ufanikishaji wa SLA")} /><div className="row" style={{ gap: 18 }}><Ring v={0.96} size={100} stroke={9} color="var(--good)" /><div className="small mute">{t(t3("P1 1 小时 · P2 4 小时 · P3 24 小时；数据请求 48 小时", "P1 1 h · P2 4 h · P3 24 h; data requests 48 h", "P1 saa 1 · P2 saa 4 · P3 saa 24"))}</div></div></Panel>
          <Panel className="in in-3"><Head title={t3("智能体回复质量", "Agent reply quality", "Ubora wa majibu")} /><Spark data={[88, 90, 91, 93, 94, 95, 96]} color="var(--good)" h={60} /><div className="small mute" style={{ marginTop: 6 }}>{t(t3("人审通过率 96% · 有出处率 100% · 被撤回 0", "Human approval rate 96% · sourced 100% · recalled 0", "Kiwango cha idhini 96%"))}</div></Panel>
          <Panel className="span3 in in-4"><Head title={t3("按类别", "By category", "Kwa aina")} /><div className="tbl"><table><thead><tr><th>{t(t3("类别", "Category", "Aina"))}</th><th>{t(t3("工单", "Tickets", "Tiketi"))}</th><th>{t(t3("自动解决", "Auto-resolved", "Otomatiki"))}</th><th>{t(t3("首响", "First response", "Jibu la kwanza"))}</th><th>{t(t3("满意度", "CSAT", "Kuridhika"))}</th></tr></thead><tbody>{[[t(t3("下载 / 离线包", "Downloads / packs", "Upakuaji")), 142, "89%", "2 min", 4.8], [t(t3("报表", "Reports", "Ripoti")), 64, "94%", "3 min", 4.9], [t(t3("排课 / 直播", "Schedule / live", "Ratiba")), 37, "52%", "6 min", 4.6], [t(t3("账号 / 登录", "Account / sign-in", "Akaunti")), 58, "0%", "9 min", 4.5], [t(t3("数据请求", "Data requests", "Maombi ya data")), 9, "0%", "14 min", 4.7]].map((r) => <tr key={r[0] as string}><td><b>{r[0] as string}</b></td><td className="num">{r[1] as number}</td><td>{r[2] as string}</td><td>{r[3] as string}</td><td>{r[4] as number}</td></tr>)}</tbody></table></div></Panel>
        </div>
      )}
    </Shell>
  );
}
