"use client";
import Shell from "@/components/Shell";
import { Panel, Head, Badge, Bar, Stat } from "@/components/ui";
import { opsRole, opsNav } from "@/lib/roles";
import { useT, t3 } from "@/lib/i18n";

export default function Compliance() {
  const t = useT();
  const reg = [["Singapore", "PDPA", t3("同意 · 保留 · 出境 · DPO", "consent · retention · transfer · DPO", "idhini · uhifadhi · uhamisho · DPO"), "good"], ["Nigeria", "NDPA 2023", t3("监护人同意 · 跨境条件 · 登记", "guardian consent · transfer conditions · registration", "idhini ya mlezi · masharti ya uhamisho"), "good"], ["China (teachers)", "PIPL", t3("最小化 · 告知同意 · 不落地媒体节点", "minimisation · notice & consent · no media node in China", "upunguzaji · taarifa na idhini"), "warn"], ["Kenya", "DPA 2019", t3("试点前法务备忘", "legal memo before pilot", "memo ya kisheria kabla ya majaribio"), ""]];
  return (
    <Shell role={opsRole} nav={opsNav} title={t3("合规与审计", "Compliance & audit", "Uzingatiaji na ukaguzi")} sub={t3("协会为数据控制者，平台为处理者，学校为联合控制方；合规登记册逐国、逐义务、逐证据", "Association as controller, platform as processor, schools as joint controllers; the register is per country, obligation and evidence", "Chama = mdhibiti, jukwaa = mchakataji, shule = wadhibiti wa pamoja")} net={3}>
      <div className="grid c4">
        <Panel className="in in-1"><Stat value={99} suffix="%" label={t3("家长同意覆盖", "parental consent coverage", "idhini ya wazazi")} /></Panel>
        <Panel className="in in-2"><Stat value={3} label={t3("数据请求（导出 2 · 删除 1）· 均 <48h", "data requests (2 export, 1 delete) · all <48h", "maombi ya data")} /></Panel>
        <Panel className="in in-3"><Stat value={0} label={t3("安全事件", "security incidents", "matukio ya usalama")} /></Panel>
        <Panel className="in in-4"><Stat value={100} suffix="%" label={t3("写动作有审批哈希", "write actions with approval hash", "vitendo vya kuandika vyenye hashi")} /></Panel>
        <Panel className="span2 in in-2"><Head title={t3("合规登记册", "Compliance register", "Rejista ya uzingatiaji")} /><div className="tbl"><table><thead><tr><th>{t(t3("范围", "Scope", "Upeo"))}</th><th>{t(t3("法规", "Law", "Sheria"))}</th><th>{t(t3("义务", "Obligations", "Wajibu"))}</th><th>{t(t3("状态", "Status", "Hali"))}</th></tr></thead><tbody>{reg.map(([c, l, o, s]) => <tr key={c as string}><td><b>{c as string}</b></td><td className="mono small">{l as string}</td><td className="small">{t(o as never)}</td><td><Badge tone={s as never}>{s === "good" ? t(t3("法务已确认", "Legal confirmed", "Imethibitishwa")) : s === "warn" ? t(t3("备忘待签", "Memo pending", "Memo inasubiri")) : t(t3("阶段 3", "Phase 3", "Awamu ya 3"))}</Badge></td></tr>)}</tbody></table></div></Panel>
        <Panel className="span2 in in-3"><Head title={t3("数据流与主权", "Data flows & sovereignty", "Mtiririko wa data")} /><ul className="list small">{[[t3("核心数据", "Core data", "Data kuu"), "Singapore · " + t(t3("加密静态与传输", "encrypted at rest and in transit", "imesimbwa"))], [t3("学员端本地", "Learner device", "Kifaa cha mwanafunzi"), t(t3("加密本地库 · 注销后 30 天删除", "encrypted local store · deleted 30 days after account closure", "hifadhi iliyosimbwa · kufutwa siku 30"))], [t3("情节记忆", "Episodic memory", "Kumbukumbu"), t(t3("只追加 · 可导出 · 可删除", "append-only · exportable · deletable", "huongezwa · huhamishwa · hufutwa"))], [t3("老师数据", "Teacher data", "Data ya walimu"), t(t3("最小化 · 音色授权书存档", "minimised · voice authorisation on file", "imepunguzwa · idhini ya sauti"))], [t3("模型训练", "Model training", "Mafunzo ya modeli"), t(t3("试点期不用学员数据训练任何模型", "no learner data used to train any model during the pilot", "hakuna data ya wanafunzi kwa mafunzo"))]].map(([k, v]) => <li key={t(k as never)}><div className="t"><b>{t(k as never)}</b><span>{v as string}</span></div></li>)}</ul></Panel>
        <Panel className="span2 in in-4"><Head title={t3("审计留痕 · 最近", "Audit trail · recent", "Nyayo za ukaguzi")} /><ul className="list small mono">{[["09-05 13:58", "proposal p1 approved by teacher:wang · hash 8c1f…a9e3"], ["09-05 11:20", "export request learner:0421 fulfilled · 6h"], ["09-04 22:10", "consent form v2 signed · school:GH · 3 guardians"], ["09-04 09:02", "isolation test tenant:GH/NH PASS"], ["09-03 17:44", "memory delete learner:0388 · episodic 12 rows"]].map(([d, e]) => <li key={d}><span className="dim">{d}</span><div className="t"><span style={{ fontFamily: "var(--font)" }}>{e}</span></div></li>)}</ul></Panel>
        <Panel className="span2 in in-5"><Head title={t3("内容与未成年人保护", "Content & child safety", "Maudhui na usalama wa watoto")} /><dl className="kv"><dt>{t(t3("内容审核队列", "Moderation queue", "Foleni ya ukaguzi"))}</dt><dd>2 {t(t3("待审 · 共读留言", "pending · shared-reading comments", "zinasubiri"))}</dd><dt>{t(t3("直播录制告知", "Recording notice", "Taarifa ya kurekodi"))}</dt><dd>{t(t3("每堂课开始播报（三语）", "announced at the start of every class (3 languages)", "hutangazwa kila somo"))}</dd><dt>{t(t3("举报与申诉", "Report & appeal", "Ripoti na rufaa"))}</dt><dd>0 {t(t3("本月", "this month", "mwezi huu"))}</dd><dt>{t(t3("肖像与作品授权", "Image & work licences", "Idhini za picha na kazi"))}</dt><dd>186 / 186</dd></dl><Bar v={1} tone="good" /></Panel>
      </div>
    </Shell>
  );
}
