"use client";
import Shell from "@/components/Shell";
import { Panel, Head, Badge, Bar, Spark, Ring } from "@/components/ui";
import { opsRole, opsNav } from "@/lib/roles";
import { useT, t3 } from "@/lib/i18n";

export default function Network() {
  const t = useT();
  return (
    <Shell role={opsRole} nav={opsNav} title={t3("网络与分发", "Network & delivery", "Mtandao na usambazaji")} sub={t3("云中立部署矩阵：每个第三方都有备选；按目标国实测择优", "Cloud-neutral matrix: every third party has a fallback; chosen by in-country measurement", "Matriki ya wingu: kila mhusika ana mbadala")} net={3}>
      <div className="grid c4">
        {[[t3("拉各斯 4G", "Lagos 4G", "Lagos 4G"), .82, "good"], [t3("阿布贾 3G", "Abuja 3G", "Abuja 3G"), .61, "warn"], [t3("蒙巴萨 3G", "Mombasa 3G", "Mombasa 3G"), .58, "warn"], [t3("郑州 → 新加坡", "Zhengzhou → Singapore", "Zhengzhou → Singapore"), .95, "good"]].map(([n, v, tone], i) => <Panel key={i} className={`in in-${i + 1}`} style={{ textAlign: "center" }}><div className="small mute">{t(n as never)}</div><Ring v={v as number} size={100} stroke={9} color={tone === "good" ? "var(--good)" : "var(--warn)"} /><div className="small mute">{t(t3("可用性 · 24h", "availability · 24h", "upatikanaji · 24h"))}</div></Panel>)}
        <Panel className="span2 in in-3"><Head title={t3("部署矩阵", "Deployment matrix", "Matriki ya usambazaji")} /><div className="tbl"><table><thead><tr><th>{t(t3("依赖", "Dependency", "Utegemezi"))}</th><th>{t(t3("主选", "Primary", "Kuu"))}</th><th>{t(t3("备选", "Fallback", "Mbadala"))}</th><th>{t(t3("状态", "Status", "Hali"))}</th></tr></thead><tbody>{[[t3("计算 / 编排", "Compute", "Kompyuta"), "Alibaba ACK (SG)", "EKS · GKE · AKS", "good"], [t3("对象存储", "Object storage", "Hifadhi"), "OSS", "S3 · GCS · MinIO", "good"], ["RTC", "Zoom (deep link)", "Agora · TRTC · LiveKit", "good"], ["CDN", "Cloudflare", "Alibaba CDN · Akamai", "warn"], ["LLM / ASR / TTS", "Model Studio", "Claude · Gemini · open", "good"], [t3("跨境加速", "Cross-border", "Uharakishaji"), "GA / CEN", t(t3("他厂 / 专线", "other / leased line", "mengine"))!, "good"]].map(([d, p, f, s]) => <tr key={typeof d === "string" ? d : t(d as never)}><td><b>{typeof d === "string" ? d : t(d as never)}</b></td><td>{p as string}</td><td className="small mute">{f as string}</td><td><Badge tone={s as never}>{s === "good" ? t(t3("正常", "Healthy", "Sawa")) : t(t3("阿布贾切换备选 CDN", "Abuja on fallback CDN", "Abuja kwenye CDN mbadala"))}</Badge></td></tr>)}</tbody></table></div></Panel>
        <Panel className="span2 in in-4"><Head title={t3("内容包下载成功率 · 7 天", "Pack download success · 7 days", "Mafanikio ya upakuaji · siku 7")} /><Spark data={[88, 90, 84, 93, 95, 96, 97]} color="var(--good)" h={70} /><div className="small mute" style={{ marginTop: 8 }}>{t(t3("学校局域网缓存点上线后（W2），阿布贾从 84% 升到 96%；夜间 02:00 推送占 71%。", "After the school LAN cache point went live (W2), Abuja rose from 84% to 96%; 71% of pushes happen at 02:00.", "Baada ya hifadhi ya shule (W2), Abuja iliongezeka kutoka 84% hadi 96%."))}</div><div style={{ marginTop: 10 }} className="small"><div className="between"><span>{t(t3("CDN 流量 · 本月", "CDN traffic · this month", "Trafiki ya CDN"))}</span><b>412 GB / 600</b></div><Bar v={0.69} /></div></Panel>
        <Panel className="span2 in in-5"><Head title={t3("直播质量 · 三段路径 · 本周", "Live quality · three segments · this week", "Ubora wa moja kwa moja · wiki hii")} /><ul className="list small">{[[t3("中国老师 → 新加坡", "China → Singapore", "Uchina → Singapore"), "RTT 118 ms · loss 1.2%", "good"], [t3("新加坡核心", "Singapore core", "Kiini"), "RTT <5 ms", "good"], [t3("新加坡 → 拉各斯", "Singapore → Lagos", "Singapore → Lagos"), "RTT 312 ms · loss 6.8% · " + t(t3("二级降级 3 次", "3 level-2 events", "matukio 3 ya kiwango 2")), "warn"]].map(([n, v, s]) => <li key={t(n as never)}><Badge tone={s as never}>{s === "good" ? "OK" : "!"}</Badge><div className="t"><b>{t(n as never)}</b><span className="mono">{v as string}</span></div></li>)}</ul></Panel>
        <Panel className="span2 in in-6" gold><Head title={t3("成本护栏", "Cost guardrails", "Vizuizi vya gharama")} /><dl className="kv"><dt>{t(t3("租户预算", "Tenant budget", "Bajeti"))}</dt><dd>USD 400 / {t(t3("月", "month", "mwezi"))} · {t(t3("已用 238", "used 238", "imetumika 238"))}</dd><dt>{t(t3("超限动作", "Over-limit action", "Kitendo cha kuzidi"))}</dt><dd>{t(t3("降级到录播 + 本地复习，不静默烧钱", "degrade to recordings + local review, never burn silently", "shuka hadi rekodi, kamwe usichome kimya"))}</dd><dt>{t(t3("告警", "Alerts", "Tahadhari"))}</dt><dd>{t(t3("80% 预算 · CDN 单价异常 · RTC 分钟数", "80% budget · CDN unit price anomaly · RTC minutes", "80% bajeti · bei ya CDN · dakika za RTC"))}</dd></dl></Panel>
      </div>
    </Shell>
  );
}
